test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /mnt/lx/LIIF-code/liif-main/load/benchmark/B100/LR_bicubic/X4
      root_path_2: /mnt/lx/LIIF-code/liif-main/load/benchmark/B100/HR
  wrapper:
    name: sr-attack
    args:
      cell: 2
  batch_size: 1
eval_type: benchmark-2
eval_bsize: 30000
scale : 2

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}